jenkins_user: "jenkins"
jenkins_group: "edx"
jenkins_war_name: jenkins_1.651.3.war
jenkins_port: 8080
jenkins_war_url: https://s3.amazonaws.com/edx-testeng-tools/jenkins/{{ jenkins_war_name }}
jenkins_home: /var/lib/jenkins
java_home: /usr/lib/jvm/java-8-openjdk-amd64
jenkins_configuration_git_url: https://github.com/edx/jenkins-configuration.git
jenkins_config_files: /init-configs
jenkins_config_templates: "{{ role_path }}/files"

jenkins_debian_pkgs:
  - git
  - curl
  - openjdk-8-jdk
  - nginx
  - maven
  - daemon
  - psmisc

jenkins_configuration_scripts:
  - 1addJarsToClasspath.groovy
  - 2checkInstalledPlugins.groovy
  - 3mainConfiguration.groovy
  - 3shutdownCLI.groovy
  - 4configureEc2Plugin.groovy
  - 4configureGHOAuth.groovy
  - 4configureGHPRB.groovy
  - 4configureGit.groovy
  - 4configureHipChat.groovy
  - 4configureJobConfigHistory.groovy
  - 4configureMailerPlugin.groovy
  - 5addSeedJob.groovy
  - 5createLoggers.groovy
  - 6importCredentials.groovy

jenkins_pinned_plugins:
  - name: 'antisamy-markup-formatter'
    version: '1.3'
    group: 'org.jenkins-ci.plugins'
  - name: 'script-security'
    version: '1.27'
    group: 'org.jenkins-ci.plugins'
  - name: 'mailer'
    version: '1.16'
    group: 'org.jenkins-ci.plugins'
  - name: 'cvs'
    version: '2.12'
    group: 'org.jenkins-ci.plugins'
  - name: 'ldap'
    version: '1.11'
    group: 'org.jenkins-ci.plugins'
  - name: 'windows-slaves'
    version: '1.0'
    group: 'org.jenkins-ci.plugins'
  - name: 'ant'
    version: '1.2'
    group: 'org.jenkins-ci.plugins'
  - name: 'matrix-auth'
    version: '1.2'
    group: 'org.jenkins-ci.plugins'
  - name: 'matrix-project'
    version: '1.4.1'
    group: 'org.jenkins-ci.plugins'
  - name: 'credentials'
    version: '1.24'
    group: 'org.jenkins-ci.plugins'
  - name: 'ssh-credentials'
    version: '1.11'
    group: 'org.jenkins-ci.plugins'
  - name: 'plain-credentials'
    version: '1.1'
    group: 'org.jenkins-ci.plugins'
  - name: 'external-monitor-job'
    version: '1.4'
    group: 'org.jenkins-ci.plugins'
  - name: 'translation'
    version: '1.12'
    group: 'org.jenkins-ci.plugins'
  - name: 'subversion'
    version: '2.4.5'
    group: 'org.jenkins-ci.plugins'
  - name: 'junit'
    version: '1.3'
    group: 'org.jenkins-ci.plugins'
  - name: 'pam-auth'
    version: '1.2'
    group: 'org.jenkins-ci.plugins'
  - name: 'maven-plugin'
    version: '2.8'
    group: 'org.jenkins-ci.main'
  - name: 'ssh-slaves'
    version: '1.9'
    group: 'org.jenkins-ci.plugins'
  - name: 'javadoc'
    version: '1.3'
    group: 'org.jenkins-ci.plugins'
  - name: 'ghprb'
    version: '1.22.4'
    group: 'org.jenkins-ci.plugins'
  - name: 'ec2'
    version: '1.28'
    group: 'org.jenkins-ci.plugins'
  - name: 'job-dsl'
    version: '1.45'
    group: 'org.jenkins-ci.plugins'
  - name: 'github-oauth'
    version: '0.24'
    group: 'org.jenkins-ci.plugins'
  - name: 'gradle'
    version: '1.24'
    group: 'org.jenkins-ci.plugins'
  - name: 'hipchat'
    version: '0.1.9'
    group: 'org.jvnet.hudson.plugins'
  - name: 'jobConfigHistory'
    version: '2.10'
    group: 'org.jenkins-ci.plugins'

